// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPaP4D9XAkk9CjD3F6w6QZ87cyTYs4uWk',
    appId: '1:409930007294:web:e42a7c92885f7d5ba5dbaf',
    messagingSenderId: '409930007294',
    projectId: 'gethubb-a78de',
    authDomain: 'gethubb-a78de.firebaseapp.com',
    storageBucket: 'gethubb-a78de.appspot.com',
    measurementId: 'G-1CLRV1JN40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkDqW_2vEDgojM9MbFVsh0L1ZAH_HS1RQ',
    appId: '1:409930007294:android:90c7484b8482f4d1a5dbaf',
    messagingSenderId: '409930007294',
    projectId: 'gethubb-a78de',
    storageBucket: 'gethubb-a78de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKHPwqqAr7KcxR1nct9vNUt_5CUxSAys',
    appId: '1:409930007294:ios:7663528a8b2832bfa5dbaf',
    messagingSenderId: '409930007294',
    projectId: 'gethubb-a78de',
    storageBucket: 'gethubb-a78de.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASKHPwqqAr7KcxR1nct9vNUt_5CUxSAys',
    appId: '1:409930007294:ios:454936971e822e52a5dbaf',
    messagingSenderId: '409930007294',
    projectId: 'gethubb-a78de',
    storageBucket: 'gethubb-a78de.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
